"""initial schema

Revision ID: 66cc1100f4f8
Revises: 
Create Date: 2026-08-27 21:57:54.559575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66cc1100f4f8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob_sha256', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_blob_sha256'), 'document', ['blob_sha256'], unique=False)
    op.create_table('extraction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('extractor_version', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ok', 'partial', 'invalid_response', 'failed')", name='ck_extraction_status'),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('carrier_name', sa.Text(), nullable=False),
    sa.Column('policy_number', sa.Text(), nullable=False),
    sa.Column('line_of_business', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_text_span', sa.Text(), nullable=True),
    sa.Column('validation_error', sa.Text(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_term',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('carrier_name', sa.Text(), nullable=True),
    sa.Column('policy_number', sa.Text(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('total_premium', sa.Text(), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('promoted_from_extraction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['promoted_from_extraction_id'], ['extraction.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('renewal_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('prior_document_id', sa.Integer(), nullable=False),
    sa.Column('renewal_document_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.id'], ),
    sa.ForeignKeyConstraint(['prior_document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['renewal_document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('renewal_run_id', sa.Integer(), nullable=False),
    sa.Column('prior_term_id', sa.Integer(), nullable=False),
    sa.Column('renewal_term_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prior_term_id'], ['policy_term.id'], ),
    sa.ForeignKeyConstraint(['renewal_run_id'], ['renewal_run.id'], ),
    sa.ForeignKeyConstraint(['renewal_term_id'], ['policy_term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('correction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('extracted_field_id', sa.Integer(), nullable=True),
    sa.Column('field_path', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('corrected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("kind IN ('wrong_value', 'omission', 'hallucination')", name='ck_correction_kind'),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extracted_field.id'], ),
    sa.ForeignKeyConstraint(['extraction_id'], ['extraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insured_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_term_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('descriptor', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['policy_term_id'], ['policy_term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coverage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_term_id', sa.Integer(), nullable=False),
    sa.Column('insured_item_id', sa.Integer(), nullable=True),
    sa.Column('coverage_code', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('limit_value', sa.Text(), nullable=True),
    sa.Column('limit_basis', sa.Text(), nullable=True),
    sa.Column('deductible_value', sa.Text(), nullable=True),
    sa.Column('premium', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['insured_item_id'], ['insured_item.id'], ),
    sa.ForeignKeyConstraint(['policy_term_id'], ['policy_term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('difference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('field_path', sa.Text(), nullable=False),
    sa.Column('prior_value', sa.Text(), nullable=True),
    sa.Column('renewal_value', sa.Text(), nullable=True),
    sa.Column('materiality', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.CheckConstraint("materiality IN ('material', 'informational', 'noise')", name='ck_difference_materiality'),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comparison_id', sa.Integer(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparison.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reclassification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difference_id', sa.Integer(), nullable=False),
    sa.Column('from_materiality', sa.Text(), nullable=False),
    sa.Column('to_materiality', sa.Text(), nullable=False),
    sa.Column('rule_id', sa.Text(), nullable=False),
    sa.Column('reclassified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['difference_id'], ['difference.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reclassification')
    op.drop_table('draft')
    op.drop_table('difference')
    op.drop_table('coverage')
    op.drop_table('insured_item')
    op.drop_table('correction')
    op.drop_table('comparison')
    op.drop_table('renewal_run')
    op.drop_table('policy_term')
    op.drop_table('extracted_field')
    op.drop_table('policy')
    op.drop_table('extraction')
    op.drop_index(op.f('ix_document_blob_sha256'), table_name='document')
    op.drop_table('document')
    op.drop_table('client')
    # ### end Alembic commands ###
