"""users and sessions

Revision ID: 13322ab22f91
Revises: de63e5e41ffe
Create Date: 2026-09-05 21:26:24.115585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13322ab22f91'
down_revision: Union[str, Sequence[str], None] = 'de63e5e41ffe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_app_user_email_lower', 'app_user', [sa.literal_column('lower(email)')], unique=True)
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_sha256', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_session_token_sha256'), 'user_session', ['token_sha256'], unique=True)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping/adding several indexes on
    # unrelated tables (carrier, client, document, document_link, policy,
    # policy_billing_type). Those are drift between models.py and hand-written
    # indexes from earlier migrations (trigram indexes, DESC indexes) that are
    # not represented as SQLAlchemy Index() objects. They are out of scope for
    # this task and have been removed by hand so this migration only touches
    # app_user and user_session.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_session_token_sha256'), table_name='user_session')
    op.drop_table('user_session')
    op.drop_index('uq_app_user_email_lower', table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
